package org.example.transactionmonitoringbackend.entity;


import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

import java.time.LocalDateTime;


/*
 * JPA mapping for alert records generated by rule checks.
 * This entity is stored in table "alerts".
 */
@Table(name = "alerts")
@Entity
public class Alert {
    /*
     * Primary key of alerts table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * Transaction id that triggered this alert.
     * JSON field name is "transaction_id".
     */
    @JsonProperty("transaction_id")
    @Column(name = "transaction_id", nullable = false)
    private Long transactionId;

    /*
     * Rule id that produced this alert.
     * JSON field name is "rule_id".
     */
    @JsonProperty("rule_id")
    @Column(name = "rule_id" ,nullable = false)
    private Long ruleId;

    /*
     * Current workflow status of the alert.
     * Stored as string enum in database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertStatus status = AlertStatus.OPEN;

    /*
     * Risk severity assigned when alert is created.
     * Stored as string enum in database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertSeverity severity = AlertSeverity.LOW;

    /*
     * Creation time of this alert row.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /*
     * Initialize create time when a new Alert object is created.
     */
    public Alert() {
        this.createdAt = LocalDateTime.now();
    }

    public AlertSeverity getSeverity() {
        return severity;
    }

    public void setSeverity(AlertSeverity severity) {
        this.severity = severity;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    public Long getRuleId() {
        return ruleId;
    }

    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    public AlertStatus getStatus() {
        return status;
    }

    public void setStatus(AlertStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
